# Generated by Django 4.2 on 2026-01-04 20:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('INAC', 'Inactive')], default='INAC', max_length=20)),
                ('subject', models.CharField(choices=[('PROGRAM', 'Programming'), ('EN', 'English'), ('DESIGN', 'Design')], max_length=50)),
                ('duration_month', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Active'), ('INAC', 'Inactive')], default='INAC', max_length=20)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message="Telefon raqami aynan 9 ta raqamdan iborat bo'lishi kerak.", regex='^[0-9]{9}$')])),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['firstname', 'lastname'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('JUNIOR', 'Junior'), ('MIDDLE', 'Middle'), ('SENIOR', 'Senior')], default='JUNIOR', max_length=20)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('INAC', 'Inactive')], default='INAC', max_length=20)),
                ('course', models.ManyToManyField(blank=True, related_name='mentors', to='itpark.course')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentors',
                'ordering': ['firstname', 'lastname'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_type', models.CharField(choices=[('ODD', 'Odd'), ('EVEN', 'Even'), ('Every', 'Everyday')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itpark.course')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itpark.mentor')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['schedule_type'],
            },
        ),
    ]
